//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Amirhossein Eskini github: @amirhossein7
//

import UIKit

class ___VARIABLE_productName:identifier___Presenter: ViewToPresenter___VARIABLE_productName:identifier___Protocol {

    weak var view: PresenterToView___VARIABLE_productName:identifier___Protocol?
    var interactor: PresenterToInteractor___VARIABLE_productName:identifier___Protocol?
    var router: PresenterToRouter___VARIABLE_productName:identifier___Protocol?


}

extension ___VARIABLE_productName:identifier___Presenter: InteractorToPresenter___VARIABLE_productName:identifier___Protocol {
    
}
