//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Amirhossein Eskini github: @amirhossein7
//

import UIKit

class ___VARIABLE_productName:identifier___ViewController: UIViewController {

    static let nibName = "___VARIABLE_productName:identifier___ViewController"
	var presenter: ViewToPresenter___VARIABLE_productName:identifier___Protocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}


extension ___VARIABLE_productName:identifier___ViewController: PresenterToView___VARIABLE_productName:identifier___Protocol {
    
}
